export const LOGIN = "LOGIN";
export const LOAD_USER = "LOAD_USER";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const NEW_CUSTOMER = "NEW_CUSTOMER";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const SINGLE_CUSTOMER = "SINGLE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";

export const NEW_PRICE = "NEW_PRICE";
export const UPDATE_PRICE = "UPDATE_PRICE";
export const GET_PRICES = "GET_PRICES";
export const GET_CURRENT_PRICE = "GET_CURRENT_PRICE";
export const DELETE_PRICE = "DELETE_PRICE";

export const NEW_TRANSECTION = "NEW_TRANSECTION";
export const GET_TRANSECTIONS = "GET_TRANSECTIONS";
export const SINGLE_TRANSECTION = "SINGLE_TRANSECTION";
export const UPDATE_TRANSECTION = "UPDATE_TRANSECTION";
export const DELETE_TRANSECTION = "DELETE_TRANSECTION";
export const TOTAL_TRANSECTION = "TOTAL_TRANSECTION";
